version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    networks:
      - localnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    image: backend
    container_name: backend
    networks:
      - localnetwork
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ~/.aws:/root/.aws

networks:
  localnetwork:

volumes:
  db:
    driver: local